apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spin
    cluster: getuserinfo
  name: getuserinfo
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: getuserinfo
  strategy: {}
  template:
    metadata:
      labels:
        app: spin
        cluster: getuserinfo
    spec:

      volumes:
      - name: getuserinfo-secrets
        secret:
          defaultMode: 420
          secretName: getuserinfo

      containers:
      - name: getuserinfo
        image: authz-getuserinfo:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz/liveness
            port: 8080
          failureThreshold: 3
          periodSeconds: 30
          initialDelaySeconds: 3
          timeoutSeconds: 40
        readinessProbe:
          httpGet:
            path: /healthz/readiness
            port: 8080
          failureThreshold: 3
          periodSeconds: 30
          initialDelaySeconds: 3
          timeoutSeconds: 40

        startupProbe:
          httpGet:
            path: /healthz/startup
            port: 8080
          failureThreshold: 3
          periodSeconds: 30
          initialDelaySeconds: 3
          timeoutSeconds: 40

        env:
        - name: CONFIGPATH
          value: /opt/getuserinfo/config.yaml

        volumeMounts:
        - name: getuserinfo-secrets
          mountPath: /opt/getuserinfo
          readOnly: true






status: {}
