
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# set these across the board in one place
namePrefix: authz-
commonLabels:
  app: spin
  cluster: authz-getuserinfo

resources:
- service.yaml
- deployment.yaml
- hpa.yaml

# configfile is used as key
secretGenerator:
- files:
  - config.yaml
  name: getuserinfo
  namespace: spinnaker
